#!/usr/bin/env bash
# copying a file from local host to server
if ["${4}" -eq 4]
then
    PATH_TO_FILE = $1
    IP = $2
    USERNAME = $3
    PATH_TO_SSH_KEY = $4

    scp -O $PATH_TO_FILE $USERNAME@$IP:$PATH_TO_SSH_KEY
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
