#!/usr/bin/env bash
# installing nginx and adding Hell world text

sudo apt-get update -y
sudo apt-get full-upgrade -y
sudo apt-get install nginx -y
sudo ufw enable
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
