#!/usr/bin/env bash
# installing nginx  web server and adding Hell world ti indxe
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
