#!/usr/bin/env bash
# Custom http response header
# sed is the command used to it
apt-get -y  update
apt-get -y install nginx
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME" /etc/nginx/sites-available/default
service nginx restart
