#!/usr/bin/env bash
# Custom http response header
sudo apt-get update -y
sudo apt-get install nginx
sudo service nginx start
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME" /etc/nginx/sites-available/default
sudo service nginx restart
