#!/usr/bin/env bash
# Ubuntu container’s Nginx installation from listening on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo rm /run/nginx.pid
