#!/usr/bin/env bash
# Ubuntu container’s Nginx installation from listening on port 80
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
echo "" | sudo dd status=none of=/var/run/nginx.pid
sudo rm /run/nginx.pid
