#!/usr/bin/env bash
#displays number from 1 to 100

counter=1
while (( counter <= 100 ));do
	if (( counter % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( counter % 3 == 0 ))
	then
		echo "Fizz"
	elif (( counter % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
	(( counter++))
done
