#!/usr/bin/env bash
#This script print "Best School" 10x using while loop

var=1
while [ $var -le 10 ];
do
	if [ $var -eq 4 ];
	then
		echo "bad luck"
	elif [ $var -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((var++))
done
