#!/usr/bin/env bash
# run nginx as a non root user nginx
adduser -s /bin/false nginx
cat /etc/passwd | grep -i nginx
sudo sed -i 'user nginx;' /etc/nginx/nginx.conf
sudo sed 's/80/8080' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart 
