#!/usr/bin/env bash
# run nginx as a non root user nginx
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 'user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start 
