#!/usr/bin/env bash
# run nginx as a non root user nginx
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 'li user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart 
